### ISSUE TITLE
Not only Windows?

### ISSUE THREAD

**Issue by zhangchen-qinyinghua** [hjk41/MxNet.cpp#1]
hi, @hjk41 
I think this project should be portable enough to run in a lot of platforms and with a lot of C/CPP compilers, not only Windows and VS.
So what about revising the README a bit?
https://github.com/hjk41/MxNet.cpp/blob/master/README.txt

**Comment by hjk41** [comment]
This code is actually moved from the binary distribution of Windows. I was
just being lazy...

Let me setup a general project for that.

On Wed, Dec 23, 2015 at 10:03 AM, Zhang Chen <notifications@github.com>
wrote:

> hi, @hjk41 <https://github.com/hjk41>
> I think this project should be portable enough to run in a lot of
> platforms and with a lot of C/CPP compilers, not only Windows and VS
> So what about revising the README a bit?
> https://githubcom/hjk41/MxNetcpp/blob/master/READMEtxt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hjk41/MxNet.cpp/issues/1>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by hjk41** [comment]
Just reorganized the folders. MxNetCpp.h goes to include, and MxNetCPP.cpp goes to src. I will push the updated VS solution soon. Let's use this as a base for developing CPP wrapper.

**Comment by zhangchen-qinyinghua** [comment]
It looks good.
I will try porting my code here.

**Comment by hjk41** [comment]
@zhangchen-qinyinghua I think we need to share the work load. How about you implement the current interface, and try to build a MLP based on this interface? I will write a program that extracts all the operators into a .h file so we don't need to wrap all the operators one by one.

**Comment by zhangchen-qinyinghua** [comment]
@hjk41 
I am currently just trying to implement the Symbol and Operator and Executor interface in MxNetCpp, trying to build a Lenet.

How do you think we can expose the operators?
What I can think of is using the name of the operators, like this:

Operator("Convolution",...);
Operator("BatchNorm",...);

**Comment by hjk41** [comment]
I will write a program that enumerates all the operators and create a .h
file that contains functions like:
FullyConnected(Symbol weight, Symbol bias, ...)
I think this will make writing the program easier, since you don't need to
look for the exact string, you can simply rely on the IDE to give you hint.

For now, you can simple use Operator("FullyConnected", ...). Since the .h
file will also translate to this interface anyway.

On Thu, Dec 24, 2015 at 10:44 AM, Zhang Chen <notifications@github.com>
wrote:

> @hjk41 <https://github.com/hjk41>
> I am currently just trying to implement the Symbol and Operator and
> Executor interface in MxNetCpp, trying to build a Lenet.
>
> How do you think we can expose the operators?
> What I can think of is using the name of the operators, like this:
>
> Operator("Convolution",...);
> Operator("BatchNorm",...);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hjk41/MxNet.cpp/issues/1#issuecomment-167030396>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by zhangchen-qinyinghua** [comment]
Fine.
Let's just do it like what you said, before any better idea comes up.

**Comment by hjk41** [comment]
I am thinking of this kind of interface:

Operator fc("FullyConnected");
Symbol fclayer = fc.SetParam("num_hidden", "28")
                   .SetParam("no_bias", "false")
Executor e = fclayer.Bind(input, grad, ...)
e.Forward()
...

Or simply
Executor e = Operator("FullyConnected").SetParam("num_hidden", "28")
                                       .SetParam("no_bias", "false")
                                       .Bind(input, grad, ...)
...



On Thu, Dec 24, 2015 at 10:54 AM, Zhang Chen <notifications@github.com>
wrote:

> Fine.
> Let's just do it like what you said, before any better idea comes up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hjk41/MxNet.cpp/issues/1#issuecomment-167032064>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by zhangchen-qinyinghua** [comment]
Check the way I was using in my mnist example:
https://github.com/zhangchen-qinyinghua/mxnet/blob/master/example/cpp/mnist-src/mnist.cc#L27-L53

**Comment by hjk41** [comment]
Looks good to me. We just need to make sure we only use the c api.

On Thu, Dec 24, 2015 at 11:27 AM, Zhang Chen <notifications@github.com>
wrote:

> Check the way I was using in my mnist example:
>
> https://github.com/zhangchen-qinyinghua/mxnet/blob/master/example/cpp/mnist-src/mnist.cc#L27-L53
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hjk41/MxNet.cpp/issues/1#issuecomment-167035655>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by zhangchen-qinyinghua** [comment]
Yeah.
I am now just trying to implement Symbol and Operator in MxNetCpp a kind of this way, only use the c api.

**Comment by zhangchen-qinyinghua** [comment]
@hjk41 
I currently feel the way you mentioned,

Operator fc("FullyConnected");
Symbol fclayer = fc.SetParam("num_hidden", "28")
                   .SetParam("no_bias", "false")

is a lot better.
So I gave implement of that. It is about to be finished.
