### ISSUE TITLE
Let's move to dmlc/MXNet.cpp

### ISSUE THREAD

**Issue by hjk41** [hjk41/MxNet.cpp#19]
@stereomatchingkiss @zhangchen-qinyinghua
Guys, I have created dmlc/MXNet.cpp project and pushed the current code there. Let us move to there for development and discussion.

**Comment by zhangchen-qinyinghua** [comment]
There's some bugs here.

The example lenet got core error in my machine, but it runs well with the older version mxnet library.

I'm debugging it now.

**Comment by zhangchen-qinyinghua** [comment]
@hjk41 
I've found the BUG.

The problem comes from the Optimizer, which is outdated.
The c_api.h has beed updated.
This makes the function MXOptimizerUpdate and params of ccSGD different from the old ones, and caused the core error.

So, could you please update the c_api.h?
And I will modify the codes a little to solve the problem.

**Comment by hjk41** [comment]
Sorry for late response. You also have write access to both hjk41/MxNet.cpp
and dmlc/MXNet.cpp. You can directly update the file.

On Fri, Feb 19, 2016 at 6:33 PM, Zhang Chen <notifications@github.com>
wrote:

> @hjk41 <https://github.com/hjk41>
> I've found the BUG.
>
> The problem comes from the Optimizer, which is outdated.
> The c_api.h has beed updated.
> This makes the function MXOptimizerUpdate and params of ccSGD different
> from the old ones, and caused the core error.
>
> So, could you please update the c_api.h?
> And I will modify the codes a little to solve the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hjk41/MxNet.cpp/issues/19#issuecomment-186161528>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by zhangchen-qinyinghua** [comment]
Sure.
I updated the c_api.h in a new PR.
I will close this issue.
