### ISSUE TITLE
Should we divide the MxNetCpp.cpp into parts?

### ISSUE THREAD

**Issue by zhangchen-qinyinghua** [hjk41/MxNet.cpp#2]
Because the scale of the implementation file is big, and new functions may be add to it, 
it seems that we should divide MxNetCpp.cpp into a few parts, say, ndarray.cpp, symbol.cpp etc.

**Comment by hjk41** [comment]
ok. Let's have a NDArray.cpp and a Symbol.cpp, anything else you can think
of?

On Tue, Dec 29, 2015 at 10:37 AM, Zhang Chen <notifications@github.com>
wrote:

> Because the scale of the implementation file is big, and new functions may
> be add to it,
> it seems that we should divide MxNetCppcpp into a few parts, say,
> ndarraycpp, symbolcpp etc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hjk41/MxNet.cpp/issues/2>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by zhangchen-qinyinghua** [comment]
@hjk41 
Maybe ndarray.cpp, symbol.cpp, executor.cpp are enough for now.

**Comment by hjk41** [comment]
ok. let's stick with that. We can always add more if we find new
requirements.

On Tue, Dec 29, 2015 at 6:22 PM, Zhang Chen <notifications@github.com>
wrote:

> @hjk41 <https://github.com/hjk41>
> Maybe ndarray.cpp, symbol.cpp, executor.cpp are enough for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hjk41/MxNet.cpp/issues/2#issuecomment-167761590>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by zhangchen-qinyinghua** [comment]
Ok.
I will close the issue.

**Comment by zhangchen-qinyinghua** [comment]
I also added a optimizer.cpp

**Comment by hjk41** [comment]
Could you push your current code?

On Tue, Jan 5, 2016 at 3:56 PM, Zhang Chen <notifications@github.com> wrote:

> I also added a optimizer.cpp
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hjk41/MxNet.cpp/issues/2#issuecomment-168928890>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by zhangchen-qinyinghua** [comment]
I will do the push today.
I just finish implementing MLP and LeNet with c_api interface.
Cleaning the code now.
