### ISSUE TITLE
Strange problem, could you help debug?

### ISSUE THREAD

**Issue by hjk41** [hjk41/MxNet.cpp#4]
@zhangchen-qinyinghua 
The CPP wrapper is almost done. But I am having trouble with the example. Line 60 of mlp.cpp seems to be causing the problem. If I replace it with original line, it works fine. Could you help?

**Comment by zhangchen-qinyinghua** [comment]
Ok,
I will try to find the cause tonight.

**Comment by zhangchen-qinyinghua** [comment]
@hjk41 
I know the cause.
I will make a PR to fix it.

**Comment by zhangchen-qinyinghua** [comment]
The wrapper looks nice.
I will later make a PR to the implement of infer_shape, simple_bind, etc.

**Comment by hjk41** [comment]
another problem: how do I know which ndarray is binding to which symbol when I create a new Executor? I think the current interface that uses a vector of ndarrays is not convenient. We should probably allow using a dictionary of {symbol_name:ndarray}

**Comment by zhangchen-qinyinghua** [comment]
@hjk41 
You are quite right.
I already make implements of bind function which allows using dictionary.
I will make a PR once finish cleaning the code.
Maybe I will also modify the Lenet example based on your wrapper.

**Comment by hjk41** [comment]
I think we should make MxNet.cpp a header-only library, so we don't hit the
C++ ABI problem again, what do you think?


On Tue, Jan 12, 2016 at 2:00 PM, Zhang Chen <notifications@github.com>
wrote:

> @hjk41 <https://github.com/hjk41>
> You are quite right.
> I already make implements of bind function which allows using dictionary.
> I will make a PR once finish cleaning the code.
> Maybe I will also modify the Lenet example based on your wrapper.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hjk41/MxNet.cpp/issues/4#issuecomment-170806297>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by zhangchen-qinyinghua** [comment]
I think that will be OK.
Shaw I just put the implement into a few headers?

**Comment by hjk41** [comment]
Yes. Let's move all the code to header file.

On Tue, Jan 12, 2016 at 3:53 PM, Zhang Chen <notifications@github.com>
wrote:

> I think that will be OK.
> Shaw I just put the implement into a few headers?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hjk41/MxNet.cpp/issues/4#issuecomment-170830446>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia
