### ISSUE TITLE
Operators with many inputs

### ISSUE THREAD

**Issue by zhangchen-qinyinghua** [hjk41/MxNet.cpp#6]
Some operators, SoftmaxOutput and Concat for example,
takes more than one Symbols as the inputs,

codes here:
https://github.com/dmlc/mxnet/blob/master/src/operator/concat-inl.h#L24
https://github.com/dmlc/mxnet/blob/master/src/operator/softmax_output-inl.h#L24

But the number of the input Symbols of the wrapper is not right.
This makes the Bind hard or even impossible.

**Comment by hjk41** [comment]
Humm... The code is generated with the information from
MXSymbolGetAtomicSymbolInfo. So the information is not accurate. Could you
fix it manually for now?

I will try to fix the information and generate a correct one.

On Wed, Jan 13, 2016 at 5:37 PM, Zhang Chen <notifications@github.com>
wrote:

> Some operators, SoftmaxOutput and Concat for example,
> takes more than one Symbols as the inputs,
>
> codes here:
> https://githubcom/dmlc/mxnet/blob/master/src/operator/concat-inlh#L24
>
> https://githubcom/dmlc/mxnet/blob/master/src/operator/softmax_output-inlh#L24
>
> But the number of the input Symbols of the wrapper is not right
> This makes the Bind hard or even impossible
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hjk41/MxNet.cpp/issues/6>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by zhangchen-qinyinghua** [comment]
@hjk41 
Yeah. I will fix that manually.
I think the information is not correct, which also gives a bad doc in python.

also, a bug arised by this:
https://github.com/dmlc/mshadow/issues/93

**Comment by hjk41** [comment]
@zhangchen-qinyinghua https://github.com/hjk41/MxNet.cpp/pull/7/files
Does this look okay to you?
Have you found other op that has wrong info?

**Comment by zhangchen-qinyinghua** [comment]
@hjk41 
That looks good to me.
You can merge it.

And I will try to make a PR on dictionaries Binding based on the latest code tonight.
That will make the wrapper a lot easier to use.

As far as I can see, the information of most operators in common use is right, except the Unsampling operator, which needs input.
code here:
https://github.com/dmlc/mxnet/blob/master/src/operator/upsampling-inl.h#L24
